### ISSUE TITLE
Kanban board review

### ISSUE THREAD

**Issue by Ghiftee** [Ghiftee/Microverse-Js-capstone#18]
https://github.com/Ghiftee/Microverse-Js-capstone/projects

Note:
There are two people in our team:
- Ghiftee who is student A in this project
- Tacettinkustu who is student B in this project

**Comment by Dipeshtwis** [comment]
Hi @tacettinkustu and @Ghiftee, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] For a team with 2 people - All cards with `Student C` suffix on the template should be removed from the template. **Number of cards in Backlog should be equal to 15.** Currently, you have **17 cards** in backlog.
- [x] Also decide who is `Student A`, `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
- [x] The issue should use a circle with user's avatar on each card. See the example below:

<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/22434660/127869037-f6a6909b-7c2e-4da8-a6cb-f2e1ff326702.png">

### Your's issue card look like:

![Screenshot from 2021-08-02 18-56-19](https://user-images.githubusercontent.com/22434660/127869266-aac0dfb4-8e9a-409b-adbd-194e6ac0004a.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- It's better if you mention the two name and also link who is person A and person B in [this issue](https://github.com/Ghiftee/Microverse-Js-capstone/issues/18#issue-958102835) description.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghiftee** [comment]
We removed cards with student c and assigned all the other cards to the related students

**Comment by bellom** [comment]
> https://github.com/Ghiftee/Microverse-Js-capstone/projects
> 
> Note:
> There are two people in our team

### [Optional]

As mentioned by the previous reviewer, It's better if you mention the two names and also link who is person A and person B in [this issue](https://github.com/Ghiftee/Microverse-Js-capstone/issues/18#issue-958102835) description.

**Comment by bellom** [comment]
> Hi @tacettinkustu and @Ghiftee,
> 
> 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * [x]  For a team with 2 people - All cards with `Student C` suffix on the template should be removed from the template. **Number of cards in Backlog should be equal to 15.** Currently, you have **17 cards** in backlog.
> * [x]  Also decide who is `Student A`, `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
> * [x]  The issue should use a circle with user's avatar on each card. See the example below:
> 
> <img alt="assigned_card" width="372" src="https://user-images.githubusercontent.com/22434660/127869037-f6a6909b-7c2e-4da8-a6cb-f2e1ff326702.png">
> 
> ### Your's issue card look like:
> ![Screenshot from 2021-08-02 18-56-19](https://user-images.githubusercontent.com/22434660/127869266-aac0dfb4-8e9a-409b-adbd-194e6ac0004a.png)
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> * It's better if you mention the two name and also link who is person A and person B in [this issue](https://github.com/Ghiftee/Microverse-Js-capstone/issues/18#issue-958102835) description.
> 
> Cheers and Happy coding!👏👏👏
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> **_Dipesh Kumar_**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@Ghiftee @tacettinkustu, Good job making almost all the necessary corrections from the previous reviewer, but you removed more than 5 cards on the board, you're supposed to have 15 cards, but I'm seeing 13
Screenshot:
![image](https://user-images.githubusercontent.com/31897434/127875317-9127fd0d-e9ad-4000-a7ce-17433d1234b6.png)

If I may ask, is there any issue that caused you to removed more cards?

Kindly add the missing cards.

**Comment by Ghiftee** [comment]
We removed the cards because they were for student c and the first reviewer said this:
For a team with 2 people - All cards with Student C suffix on the template should be removed from the template. Number of cards in Backlog should be equal to 15. Currently, you have 17 cards in backlog.

**Comment by bellom** [comment]
## Hi Team 👏 , 

Good job making almost all the necessary corrections from the previous reviewer. 

 ## Required Changes ♻️
 
_Check the comment above the review._

Kindly add the 2 missing cards, you have 13 cards currently in Backlog instead of 15.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ghiftee** [comment]
We have added the two cards so we have a total of 15 cards now

**Comment by carlos-ssh** [comment]
Hi @Ghiftee & @tacettinkustu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
